### ISSUE TITLE
Player kick and exception thow when using `/vanish` with Folia.

### ISSUE THREAD

**Issue by HydrolienF** [Folia-Inquisitors/SuperVanish-Folia#2]
Hi, I had an exeption when triing to vanish. 
All the usefull infos are in the logs:
```java
[18:00:58 INFO]: Hydrolien issued server command: /vanish
[18:00:58 ERROR]: Thread Region Scheduler Thread #4 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPig.getHandle(CraftPig.java:67) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPig.getHandle(CraftPig.java:8) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isInWorld(CraftEntity.java:940) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isValid(CraftEntity.java:394) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.lambda$getEntities$1(CraftRegionAccessor.java:312) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.getEntities(CraftRegionAccessor.java:308) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at de.myzelyam.supervanish.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:98) ~[SuperVanish-6.2.18.jar:?]
        at de.myzelyam.supervanish.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:44) ~[SuperVanish-6.2.18.jar:?]
        at de.myzelyam.supervanish.commands.SubCommand.hidePlayer(SubCommand.java:36) ~[SuperVanish-6.2.18.jar:?]
        at de.myzelyam.supervanish.commands.subcommands.VanishSelf.execute(VanishSelf.java:33) ~[SuperVanish-6.2.18.jar:?]
        at de.myzelyam.supervanish.commands.SubCommandMgr.execute(SubCommandMgr.java:39) ~[SuperVanish-6.2.18.jar:?]
        at de.myzelyam.supervanish.commands.VanishCommand.execute(VanishCommand.java:29) ~[SuperVanish-6.2.18.jar:?]
        at de.myzelyam.supervanish.SuperVanish.onCommand(SuperVanish.java:169) ~[SuperVanish-6.2.18.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1042) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2285) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2245) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1646) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:00:58 WARN]: [SuperVanish] Unknown exception occurred!
[18:00:58 WARN]: [SuperVanish] Please report this issue!
[18:00:58 WARN]: [SuperVanish] Message: 
[18:00:58 WARN]: [SuperVanish]   Accessing entity state off owning region's thread
[18:00:58 WARN]: [SuperVanish] General information: 
[18:00:58 WARN]: [SuperVanish]   ServerVersion: git-Folia-"25ee657" (MC: 1.20.4)
[18:00:58 WARN]: [SuperVanish]   PluginVersion: 6.2.18
[18:00:58 WARN]: [SuperVanish]   ServerPlugins: LuckPerms v5.4.117, MvndiCore v1.0.6, Vault v1.7.3-b0-folia, PlaceholderAPI v2.11.5-DEV-null, CoreProtect v22.2, MvndiStats v1.1.0, Towny v0.100.2.7, ChestShop v3.12.3-SNAPSHOT (build 401), MvndiEquipment v1.1.15, MvndiPlayer v1.0.3, Brewery v3.1.1, TownyChat v0.115, squaremap v1.2.3, MvndiMMO v1.0, ProtocolLib v5.2.0, LiteBans v2.15.0, SiegeWar v2.10.1, MapTowny v2.2.0, Chunky v1.3.92, MvndiSeasons v0.4.1, MvndiGUI v${project.version}, BetterRTP v3.6.12, MvndiAchievements v1.0.4, PotionEffectsRemover v1.0.0, MinecraftSSH v1.1.0, MvndiHunters v0.1, MvndiMobs v0.10.9, MvndiChisel v0.4.1, ChatControlRed v10.23.3, BetterHud vbeta-21, TownyResources v0.8.0, iConomy v5.25, ChunkyBorder v1.1.50, TownyMenus v0.0.8-SNAPSHOT, MvndiTowny v1.0.0, PaperMessages v1.0, TownyBlockGlitch v1.0, FlagsH v4.0.0, BigDoors vAlpha 0.1.8.50 (b-1), FarmControl v1.2.5, HexNicks v3.1.1, TAB v4.1.2, MvndiBanHooks v1.0, BukkitGreentext v3.1.5, BetterGUI v9.6, InvSeePlusPlus v0.25.2-SNAPSHOT, MvndiCrafting v1.0.4, spark v1.10.60, SmoothTimber v1.25.0, FreedomChat v1.5.2, MvndiHolders v1.2.1, MvndiCombat v1.1.13, MvndiGUIShop v1.0, GrimAC v2.3.62, InventoryRollbackPlus v1.6.14, HeadDrop v4.35, VoidWorldGenerator v1.1.0, TownyWaypoints v1.4, MvndiSiege v1.0.1,
[18:00:58 WARN]: [SuperVanish] Settings:
[18:00:58 WARN]: [SuperVanish]   MsgsVersion: 6.2.18
[18:00:58 WARN]: [SuperVanish]   Settings: ||InvisibilityFeatures.NightVisionEffect>true||InvisibilityFeatures.DisableDamage>true||InvisibilityFeatures.DisableHunger>true||InvisibilityFeatures.DisableMobTarget>true||InvisibilityFeatures.OpenChestsSilently>true||InvisibilityFeatures.DisablePressurePlates>true||InvisibilityFeatures.DisablePush>false||InvisibilityFeatures.DefaultPickUpItemsOption>false||InvisibilityFeatures.ModifyTablistPackets>true||InvisibilityFeatures.ModifyTabCompletePackets>true||InvisibilityFeatures.PreventSculkSensorActivation>true||InvisibilityFeatures.PreventTurtleEggBreaking>true||InvisibilityFeatures.DisableDripLeaf>true||InvisibilityFeatures.PreventRaidTriggering>true||InvisibilityFeatures.PreventMobSpawning>true||InvisibilityFeatures.Fly.Enable>true||InvisibilityFeatures.Fly.DisableOnReappear>true||VanishStateFeatures.AutoVanishOnJoin>false||VanishStateFeatures.ReappearOnWorldChange>false||VanishStateFeatures.ReappearOnQuit>false||VanishStateFeatures.CheckPermissionOnWorldChange>false||VanishStateFeatures.CheckPermissionOnQuit>false||VanishStateFeatures.CheckPermissionOnLogin>false||IndicationFeatures.LayeredPermissions.EnableSeePermission>true||IndicationFeatures.LayeredPermissions.LayeredSeeAndUsePermissions>false||IndicationFeatures.LayeredPermissions.MaxLevel>100||IndicationFeatures.MarkVanishedPlayersAsSpectators>true||MessageOptions.FakeJoinQuitMessages.BroadcastFakeQuitOnVanish>true||MessageOptions.FakeJoinQuitMessages.BroadcastFakeJoinOnReappear>true||MessageOptions.FakeJoinQuitMessages.AnnounceVanishReappearToAdmins>true||MessageOptions.FakeJoinQuitMessages.SendMessageOnlyToAdmins>false||MessageOptions.FakeJoinQuitMessages.SendMessageOnlyToUsers>false||MessageOptions.HideRealJoinQuitMessages>true||MessageOptions.HideAdvancementMessages>true||MessageOptions.ReappearOnQuitHideLeaveMsg>true||MessageOptions.AnnounceRealJoinQuitToAdmins>true||MessageOptions.AnnounceDeathToAdmins>true||MessageOptions.RemindVanishedOnJoin>true||MessageOptions.DisplayActionBar>true||RestrictiveOptions.PreventBlockBreaking>false||RestrictiveOptions.PreventBlockPlacing>false||RestrictiveOptions.PreventHittingEntities>false||ExternalInvisibility.ServerList.AdjustAmountOfOnlinePlayers>true||ExternalInvisibility.ServerList.AdjustListOfLoggedInPlayers>true||HookOptions.EnableEssentialsHook>true||HookOptions.EnableDynmapHook>true||HookOptions.DynmapSendJoinLeaveMessages>true||HookOptions.EnableTrailGUIHook>true||HookOptions.EnablePlaceholderAPIHook>true||HookOptions.EnableMVdWPlaceholderAPIHook>true||HookOptions.EnableCitizensHook>true||CompatibilityOptions.PlayerJoinEventPriority>HIGH||CompatibilityOptions.PlayerQuitEventPriority>HIGH||MiscellaneousOptions.UpdateChecker.Enable>true||MiscellaneousOptions.UpdateChecker.NotifyAdmins>true||ConfigVersion>6.2.18||
[18:00:58 WARN]: [SuperVanish] StackTrace: 
[18:00:58 WARN]: java.lang.IllegalStateException: Accessing entity state off owning region's thread
[18:00:58 WARN]:        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79)
[18:00:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPig.getHandle(CraftPig.java:67)
[18:00:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPig.getHandle(CraftPig.java:8)
[18:00:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isInWorld(CraftEntity.java:940)
[18:00:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isValid(CraftEntity.java:394)
[18:00:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.lambda$getEntities$1(CraftRegionAccessor.java:312)
[18:00:58 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[18:00:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.getEntities(CraftRegionAccessor.java:308)
[18:00:58 WARN]:        at SuperVanish-6.2.18.jar//de.myzelyam.supervanish.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:98)
[18:00:58 WARN]:        at SuperVanish-6.2.18.jar//de.myzelyam.supervanish.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:44)
[18:00:58 WARN]:        at SuperVanish-6.2.18.jar//de.myzelyam.supervanish.commands.SubCommand.hidePlayer(SubCommand.java:36)
[18:00:58 WARN]:        at SuperVanish-6.2.18.jar//de.myzelyam.supervanish.commands.subcommands.VanishSelf.execute(VanishSelf.java:33)
[18:00:58 WARN]:        at SuperVanish-6.2.18.jar//de.myzelyam.supervanish.commands.SubCommandMgr.execute(SubCommandMgr.java:39)
[18:00:58 WARN]:        at SuperVanish-6.2.18.jar//de.myzelyam.supervanish.commands.VanishCommand.execute(VanishCommand.java:29)
[18:00:58 WARN]:        at SuperVanish-6.2.18.jar//de.myzelyam.supervanish.SuperVanish.onCommand(SuperVanish.java:169)
[18:00:58 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:00:58 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[18:00:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1042)
[18:00:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[18:00:58 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[18:00:58 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:32)
[18:00:58 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[18:00:58 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[18:00:58 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[18:00:58 WARN]:        at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:101)
[18:00:58 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:434)
[18:00:58 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
[18:00:58 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
[18:00:58 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2285)
[18:00:58 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2245)
[18:00:58 WARN]:        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173)
[18:00:58 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1646)
[18:00:58 WARN]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407)
[18:00:58 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[18:00:58 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[18:00:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[18:00:58 WARN]: [SuperVanish] Please include this information
[18:00:58 WARN]: [SuperVanish] if you report the issue.
[18:01:09 INFO]: Hydrolien lost connection: Disconnected
```

**Comment by HSGamer** [comment]
Turn off `DisableMobTarget`
